[package]
name = "skeleton_generation"
version = "0.1.0"
authors = ["nina <nina.zimbel@web.de>"]
edition = "2018"

[dependencies]
sdl2 = "0.32"
imgui = "0.2.1"
imgui-sdl2 = "0.7.0"
gl = "0.14.0"
imgui-opengl-renderer = "0.6.0"
